language: java
dist: trusty
after_success:
- bash <(curl -s https://codecov.io/bash)
jdk:
- oraclejdk8
sudo: false
script: script/deploy.sh
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
env:
  global:
  - secure: ytPfLUXY5FbCaY/1Ql+Q4vX9HLqnn/Ba4h/ngGF0AEx4nReIP0RK+6RzAxV/vsCBHYRxVix3Uy5SILUvJSUUR9NnvSJyssu2tGBTYdBCy9i+lsR7FuGyQ87h9wLflt+AGEVjX9aBeJXK8vKEQcBw8YzJ1AWoOTCRz4rQc+mzUZuUaN1hS/0abPea6/VdOyaCUsIzDqsZRZsH7qlTP2UF5HmjeN1faLsUY0JA6gN4yqrPMPHHbb4fsHuoy1X9ETK5jld33YS5BJJK9p5/fv6eM+usWh/9VcjMBrL6LoO3ICH0L7ja/OS+H+xMGnTHNkFYCg/SNQV5tDw36A+8GasirrkI669+OYkDToW1PccIVT26PSjjt5N582vJETLBJrhlBGqKq5VDVglcNr5bJFVbv52Obm8Fa5zygjood9zkxNEoa0NdIik1MKWMXTUTW75URFuCO0Skt64su1ZCwtHKkdTgFyrrkwQowHxE7JgL5mDRdXLSPF9YeddkQy1sIoA+3rFwAGOgFDfIJZXILRqA+FAQHBxxx3CvWSJ1HWpiytRDZ+UVdObGMhEsmWP358jQalSTZdNQlTMuK1A1In3AGAV1Z2d/eeRp5AOlHhqItSvX2Lg6r9sTTxYCaE1XaHQ/ZdrCequjkDCc3B4pDMLVDWcrchrm6Lx3E+GAsT5Bd3k=
  - secure: M30KV8CocoMoLhGsfEqxDuaSQBB7WuJkqpZ5iuqiXtfaKGhbCpWpqvZKCqGtDRBFn7zxE26pPAQblSRqbhlXaU5/nvl2QhjThldsRVkq3rgkeXj2bxDOyyIqO60XneJdPpmMpVVC3iWe+vEqQ2C5t1LZFmApjhW8GPKtoB1xz5yntzV6yesqw0hZ47bBQ2pld42ybGiMEWuilLXvojMqkxJjMx+yYUrPEihfpwTQfK0j6HtxLNLzzGkrvhM8/bOO1TrtJK6tL71pZKzBvGpo0hoLh/zWmFQZY24N+ifl8K/Y34TrdZRQxIkKt+6jh0DmTsGrdoG2Czf8idOeHoYmchTZHX0Ti/wbO+kitQ61y8Ud6V9cYUrThd3zZLNaTRCUv1TPwfu7tGl1ZOgg43clbRDubh5UkSxRjLdRhMBaxnd5WBlgw+Z2B0Yg843E5fgsQo/MhLJTQqVi2/MAf65Hkian0IQBIgzHl9zQQrC+f47x8RqQtITUxWIjt8BLf0dqx1vIxau0qsizLOJbNkX36sYoFZO5XKJcoFg9dnwVVBXbmOJDzVLKF3bnfhJP+A/0/0STHUdekBhE47tyGceH9alm76Y6EG5+8ZnVnxeo4c1I+lVEwLk+WZnAC1FsE4g94zBp7lO048AXhLmpjfPlUjgpxKfSMOLkbDxGPsP4uV0=
