language: java
dist: trusty
after_success:
- bash <(curl -s https://codecov.io/bash)
jdk:
- oraclejdk8
sudo: false
script: script/deploy.sh
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
env:
  global:
  - secure: t/9+vuGHF85nzvCqasCo2j1YsTpjYJ+V7wdrhLXh0C2lVBN6zOMX+VZ8N7FFh1YtJbvImPmtugR5IE2hXALg01ZokVdIVla5UIB5bzqrVZGPEhSS//eNmBp3Ap0aqn8Gl62LUpDUnyd/ap+Xhuu5nUFIN+gROXsov1iAL+wRzyWVNbwWnOH/lqPxoAKSvpw7G83I+ehbviIL1dOkUKJm++qgq4AsLbkqKe1/MINWGDS8ySqfYW48ytr/CuF6AGI6YjxKyqcEtNRzE0ZceNAGckt4/MvmQb4GIkoPD/FadNCzn96EiOLscEQuDysXmyUfXHq6Uvku73na6E0IR+vu92pOP41BEmO6tO6D18AB6j9D+4M1HzTo4QO1Y+S8wnTusvm7PwCN7WNXT3ZtTacLoOM6EzK2HZGU3XDhpnozXWR8DYeIcHCf+5i/vzeiq8r/X29xKehvKTRNh2hkul9htrRTZIZhozWDtifNv2cYz1bBZ6dBHX3wiGyQEFsPwfjkLbTRvJ6lSmuih15h65+RLgVxrPGaHyVRmPoTiLtIJmHQY49k60Ae+IPrBcxktx4zr94MbXcIjH20NOUkoIT7ilInl5mY0QrsuJgpzLhPw9wTz7017RkoSXaui92FThYygX4ZEo7KcVe+7+mcGGToOOy/PSapM0Z8rbzUWQ91J9o=
  - secure: IT7iFtR4T2NxTJipHci48MyFg3opHZD6Xo2oJnk6TBT3gLpXW8CBlLedqo4cPR5gHtyy+V4zD8ABv6S6geJm56kgjn71cClOXFcYbwV9FO3I0IYWnM33hLpEYL0GmYYr/+IxvK9gLO6lxKJkOyJ80nozyVNjvZFtFTCuE3RqATFomCNZlY/7Pize6ns7Cvp5TjCObqVAnZax84sTJB4FPxpCFJs2i8O9SkfkSNn7e7/z7WcKey91lEN2z2l/5hmdv4KskWv1t2P8LknRKaSN76sliJakh0RBylc6hfQeaV4LJscKt1b4VSBjr+dBn4melnz5DGUzclGvwyBFnYOakxrLAvzkbXniZOqKSONSdfJ9YSIAv40LG9564nAMaIUNI9I5dJ0BX2O4pfDLml5jjuWOQL4GaAm8FH8k4qbw8gNDOfoR/bAyroUOo8aQBesut0EoM26q3JChh4NV/grT22Nx75Ko2gsMgsjlpHeIN6huDdZll4PdLquqibILm6fbO7aAaiSKt8TwtDIBn8PUUks+tOm1+lhdV662/5FJVrtauaFRHk1/BEkufQazk0+GJ+0frHbE+kuSQ9QjvEovxj7XTCfrg0+mYDPMuqBBVUdXfifAm3BSFeVwBAUZsDqxHrkSgXnHkVoiKPYidk8k9iumdSEeAiVwQ9pxeb0v6QI=
